import { and, eq, sql } from "drizzle-orm";
import { categories, listingPages, products } from "@db/schema";
import { getDb } from "../queries/connection";

export const listingIndexationModes = [
  "index",
  "noindex",
  "canonical_to_parent",
  "exclude_from_sitemap",
] as const;

export const listingSeoStatuses = ["empty", "draft", "ready", "published"] as const;
export const listingDuplicateRisks = ["low", "medium", "high"] as const;

export type ListingIndexationMode = (typeof listingIndexationModes)[number];
export type ListingSeoStatus = (typeof listingSeoStatuses)[number];
export type ListingDuplicateRisk = (typeof listingDuplicateRisks)[number];

type CategoryRow = typeof categories.$inferSelect;
type ListingRow = typeof listingPages.$inferSelect;

export function trimOrNull(value?: string | null) {
  const next = value?.trim();
  return next ? next : null;
}

export function buildCategoryListingUrl(categorySlug: string) {
  return `/catalog?cat=${categorySlug}`;
}

export function buildCategoryListingTitle(categoryName: string) {
  return `${categoryName} — каталог товаров ТЕХАКС`;
}

export function buildCategoryListingDescription(categoryName: string) {
  return `${categoryName} в интернет-магазине ТЕХАКС: актуальные товары, наличие в магазинах и удобный переход к нужным разделам.`;
}

export function scoreListingContent(fields: {
  title?: string | null;
  metaDescription?: string | null;
  h1?: string | null;
  introText?: string | null;
  bottomText?: string | null;
}) {
  const weights = [
    fields.title ? 24 : 0,
    fields.metaDescription ? 22 : 0,
    fields.h1 ? 18 : 0,
    fields.introText ? 22 : 0,
    fields.bottomText ? 14 : 0,
  ];
  return Math.min(100, weights.reduce((sum, item) => sum + item, 0));
}

export function deriveListingSeoStatus(score: number): ListingSeoStatus {
  if (score >= 85) return "published";
  if (score >= 55) return "ready";
  if (score >= 20) return "draft";
  return "empty";
}

export function normalizeCanonicalUrl(
  canonicalUrl?: string | null
): string | null {
  const value = canonicalUrl?.trim();
  if (!value) return null;
  if (value.startsWith("http://") || value.startsWith("https://")) return value;
  return value.startsWith("/") ? value : `/${value}`;
}

export function shouldNoindexCategoryListing(
  indexationMode?: string | null
): boolean {
  return indexationMode === "noindex";
}

export function shouldIncludeCategoryListingInSitemap(
  listing: ListingRow | null | undefined
) {
  if (!listing || !listing.isPublished) return true;
  return listing.indexationMode === "index";
}

export function buildCategoryListingViewModel(
  category: CategoryRow,
  listing: ListingRow | null,
  productCount: number
) {
  const title = listing?.title ?? category.metaTitle ?? buildCategoryListingTitle(category.name);
  const metaDescription =
    listing?.metaDescription ??
    category.metaDescription ??
    buildCategoryListingDescription(category.name);
  const h1 = listing?.h1 ?? category.name;
  const introText = listing?.introText ?? category.description ?? null;
  const bottomText = listing?.bottomText ?? null;
  const contentScore =
    listing?.contentScore ??
    scoreListingContent({ title, metaDescription, h1, introText, bottomText });
  const seoTextStatus = listing?.seoTextStatus ?? deriveListingSeoStatus(contentScore);
  const indexationMode = (listing?.indexationMode ?? "index") as ListingIndexationMode;
  const duplicateRisk =
    productCount === 0
      ? "high"
      : (listing?.duplicateRisk as ListingDuplicateRisk | null) ??
        (productCount < 3 ? "medium" : "low");

  return {
    id: listing?.id ?? null,
    type: "category" as const,
    categoryId: category.id,
    categoryName: category.name,
    categorySlug: category.slug,
    url: listing?.url ?? buildCategoryListingUrl(category.slug),
    title,
    metaDescription,
    h1,
    introText,
    bottomText,
    canonicalUrl: normalizeCanonicalUrl(listing?.canonicalUrl ?? null),
    indexationMode,
    seoTextStatus,
    isPublished: listing?.isPublished ?? true,
    isAutoGenerated: listing?.isAutoGenerated ?? false,
    demandScore: listing?.demandScore ?? 0,
    contentScore,
    duplicateRisk,
    productCount,
    updatedAt: listing?.updatedAt ?? null,
    createdAt: listing?.createdAt ?? null,
  };
}

export async function resolveCategoryListingBySlug(
  categorySlug: string,
  options?: { includeUnpublished?: boolean }
) {
  const db = getDb();
  const [category] = await db
    .select()
    .from(categories)
    .where(eq(categories.slug, categorySlug))
    .limit(1);

  if (!category) return null;

  const [listing, countRow] = await Promise.all([
    db
      .select()
      .from(listingPages)
      .where(
        and(
          eq(listingPages.type, "category"),
          eq(listingPages.categoryId, category.id)
        )
      )
      .limit(1)
      .then(rows => rows[0] ?? null),
    db
      .select({ productCount: sql<number>`count(*)` })
      .from(products)
      .where(and(eq(products.categoryId, category.id), eq(products.isActive, true)))
      .then(rows => Number(rows[0]?.productCount ?? 0)),
  ]);

  const effectiveListing =
    listing && (options?.includeUnpublished || listing.isPublished) ? listing : null;

  return buildCategoryListingViewModel(category, effectiveListing, countRow);
}
