import { TRPCError } from "@trpc/server";
import { and, asc, desc, eq, like, or, sql } from "drizzle-orm";
import { z } from "zod";
import { requireAbility, createRouter, protectedProcedure } from "../middleware";
import { getDb } from "../queries/connection";
import { categories, listingPages, products } from "@db/schema";
import { writeAdminAuditLog } from "../lib/admin-audit";

const listingIndexationModeSchema = z.enum([
  "index",
  "noindex",
  "canonical_to_parent",
  "exclude_from_sitemap",
]);
const listingSeoStatusSchema = z.enum(["empty", "draft", "ready", "published"]);
const listingDuplicateRiskSchema = z.enum(["low", "medium", "high"]);

function trimOrNull(value?: string | null) {
  const next = value?.trim();
  return next ? next : null;
}

function buildCategoryListingUrl(categorySlug: string) {
  return `/catalog?cat=${categorySlug}`;
}

function buildCategoryListingTitle(categoryName: string) {
  return `${categoryName} — каталог товаров ТЕХАКС`;
}

function buildCategoryListingDescription(categoryName: string) {
  return `${categoryName} в интернет-магазине ТЕХАКС: актуальные товары, наличие в магазинах и удобный переход к нужным разделам.`;
}

function scoreContent(fields: {
  title?: string | null;
  metaDescription?: string | null;
  h1?: string | null;
  introText?: string | null;
  bottomText?: string | null;
}) {
  const weights = [
    fields.title ? 24 : 0,
    fields.metaDescription ? 22 : 0,
    fields.h1 ? 18 : 0,
    fields.introText ? 22 : 0,
    fields.bottomText ? 14 : 0,
  ];
  return Math.min(100, weights.reduce((sum, item) => sum + item, 0));
}

function deriveSeoStatus(score: number) {
  if (score >= 85) return "published" as const;
  if (score >= 55) return "ready" as const;
  if (score >= 20) return "draft" as const;
  return "empty" as const;
}

type CategoryRow = typeof categories.$inferSelect;
type ListingRow = typeof listingPages.$inferSelect;

function buildCategoryListingViewModel(
  category: CategoryRow,
  listing: ListingRow | null,
  productCount: number
) {
  const title = listing?.title ?? category.metaTitle ?? buildCategoryListingTitle(category.name);
  const metaDescription =
    listing?.metaDescription ??
    category.metaDescription ??
    buildCategoryListingDescription(category.name);
  const h1 = listing?.h1 ?? category.name;
  const introText = listing?.introText ?? category.description ?? null;
  const bottomText = listing?.bottomText ?? null;
  const contentScore =
    listing?.contentScore ??
    scoreContent({ title, metaDescription, h1, introText, bottomText });
  const seoTextStatus = listing?.seoTextStatus ?? deriveSeoStatus(contentScore);
  const indexationMode = listing?.indexationMode ?? "index";
  const duplicateRisk =
    productCount === 0
      ? "high"
      : listing?.duplicateRisk ?? (productCount < 3 ? "medium" : "low");

  return {
    id: listing?.id ?? null,
    type: "category" as const,
    categoryId: category.id,
    categoryName: category.name,
    categorySlug: category.slug,
    url: listing?.url ?? buildCategoryListingUrl(category.slug),
    title,
    metaDescription,
    h1,
    introText,
    bottomText,
    canonicalUrl: listing?.canonicalUrl ?? null,
    indexationMode,
    seoTextStatus,
    isPublished: listing?.isPublished ?? true,
    isAutoGenerated: listing?.isAutoGenerated ?? false,
    demandScore: listing?.demandScore ?? 0,
    contentScore,
    duplicateRisk,
    productCount,
    updatedAt: listing?.updatedAt ?? null,
    createdAt: listing?.createdAt ?? null,
  };
}

export const listingRouter = createRouter({
  listCategoryListings: protectedProcedure
    .input(
      z
        .object({
          search: z.string().optional(),
          indexationMode: listingIndexationModeSchema.optional(),
          seoTextStatus: listingSeoStatusSchema.optional(),
        })
        .optional()
    )
    .query(async ({ ctx, input }) => {
      requireAbility(ctx, "read", "Listing");
      const db = getDb();
      const search = input?.search?.trim();
      const categoryWhere = search
        ? or(
            like(categories.name, `%${search}%`),
            like(categories.slug, `%${search}%`),
            like(categories.description, `%${search}%`)
          )
        : undefined;

      const [categoryRows, listingRows, productCountRows] = await Promise.all([
        db.select().from(categories).where(categoryWhere).orderBy(asc(categories.sortOrder), asc(categories.name)),
        db
          .select()
          .from(listingPages)
          .where(eq(listingPages.type, "category"))
          .orderBy(desc(listingPages.updatedAt)),
        db
          .select({
            categoryId: products.categoryId,
            productCount: sql<number>`count(*)`,
          })
          .from(products)
          .where(eq(products.isActive, true))
          .groupBy(products.categoryId),
      ]);

      const listingByCategoryId = new Map(
        listingRows.map(item => [item.categoryId, item] as const)
      );
      const countsByCategoryId = new Map(
        productCountRows.map(item => [item.categoryId, Number(item.productCount ?? 0)] as const)
      );

      const items = categoryRows
        .map(category =>
          buildCategoryListingViewModel(
            category,
            listingByCategoryId.get(category.id) ?? null,
            countsByCategoryId.get(category.id) ?? 0
          )
        )
        .filter(item =>
          input?.indexationMode ? item.indexationMode === input.indexationMode : true
        )
        .filter(item =>
          input?.seoTextStatus ? item.seoTextStatus === input.seoTextStatus : true
        );

      const summary = {
        total: items.length,
        custom: items.filter(item => item.id !== null).length,
        indexable: items.filter(item => item.indexationMode === "index").length,
        noindex: items.filter(item => item.indexationMode === "noindex").length,
        ready: items.filter(item => item.seoTextStatus === "ready" || item.seoTextStatus === "published").length,
        highRisk: items.filter(item => item.duplicateRisk === "high").length,
      };

      return { items, summary };
    }),

  getCategoryListing: protectedProcedure
    .input(z.object({ categoryId: z.number().int().positive() }))
    .query(async ({ ctx, input }) => {
      requireAbility(ctx, "read", "Listing");
      const db = getDb();
      const [categoryRows, listingRows, countRows] = await Promise.all([
        db.select().from(categories).where(eq(categories.id, input.categoryId)).limit(1),
        db
          .select()
          .from(listingPages)
          .where(
            and(
              eq(listingPages.type, "category"),
              eq(listingPages.categoryId, input.categoryId)
            )
          )
          .limit(1),
        db
          .select({ productCount: sql<number>`count(*)` })
          .from(products)
          .where(and(eq(products.categoryId, input.categoryId), eq(products.isActive, true))),
      ]);
      const category = categoryRows[0];

      if (!category) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Категория не найдена." });
      }

      const listing = listingRows[0] ?? null;
      return buildCategoryListingViewModel(
        category,
        listing,
        Number(countRows[0]?.productCount ?? 0)
      );
    }),

  upsertCategoryListing: protectedProcedure
    .input(
      z.object({
        categoryId: z.number().int().positive(),
        data: z.object({
          title: z.string().nullable().optional(),
          metaDescription: z.string().nullable().optional(),
          h1: z.string().nullable().optional(),
          introText: z.string().nullable().optional(),
          bottomText: z.string().nullable().optional(),
          canonicalUrl: z.string().nullable().optional(),
          indexationMode: listingIndexationModeSchema,
          seoTextStatus: listingSeoStatusSchema.optional(),
          isPublished: z.boolean().default(true),
          isAutoGenerated: z.boolean().default(false),
          demandScore: z.number().int().min(0).max(100).default(0),
          duplicateRisk: listingDuplicateRiskSchema.default("low"),
        }),
      })
    )
    .mutation(async ({ ctx, input }) => {
      requireAbility(ctx, "manage", "Listing");
      const db = getDb();
      const [category] = await db
        .select()
        .from(categories)
        .where(eq(categories.id, input.categoryId))
        .limit(1);

      if (!category) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Категория не найдена." });
      }

      const [existing] = await db
        .select()
        .from(listingPages)
        .where(
          and(
            eq(listingPages.type, "category"),
            eq(listingPages.categoryId, input.categoryId)
          )
        )
        .limit(1);

      const payload = {
        type: "category" as const,
        categoryId: input.categoryId,
        filterKey: null,
        filterValue: null,
        slug: category.slug,
        url: buildCategoryListingUrl(category.slug),
        title: trimOrNull(input.data.title),
        metaDescription: trimOrNull(input.data.metaDescription),
        h1: trimOrNull(input.data.h1),
        introText: trimOrNull(input.data.introText),
        bottomText: trimOrNull(input.data.bottomText),
        canonicalUrl:
          input.data.indexationMode === "canonical_to_parent"
            ? trimOrNull(input.data.canonicalUrl) ?? buildCategoryListingUrl(category.slug)
            : trimOrNull(input.data.canonicalUrl),
        indexationMode: input.data.indexationMode,
        seoTextStatus:
          input.data.seoTextStatus ??
          deriveSeoStatus(
            scoreContent({
              title: trimOrNull(input.data.title),
              metaDescription: trimOrNull(input.data.metaDescription),
              h1: trimOrNull(input.data.h1),
              introText: trimOrNull(input.data.introText),
              bottomText: trimOrNull(input.data.bottomText),
            })
          ),
        isPublished: input.data.isPublished,
        isAutoGenerated: input.data.isAutoGenerated,
        demandScore: input.data.demandScore,
        contentScore: scoreContent({
          title: trimOrNull(input.data.title),
          metaDescription: trimOrNull(input.data.metaDescription),
          h1: trimOrNull(input.data.h1),
          introText: trimOrNull(input.data.introText),
          bottomText: trimOrNull(input.data.bottomText),
        }),
        duplicateRisk: input.data.duplicateRisk,
        updatedBy: ctx.user.id,
        updatedAt: new Date(),
      };

      let listingId = existing?.id ?? 0;

      if (existing) {
        await db.update(listingPages).set(payload).where(eq(listingPages.id, existing.id));
      } else {
        const result = await db.insert(listingPages).values({
          ...payload,
          createdBy: ctx.user.id,
        });
        listingId = result[0].insertId;
      }

      await writeAdminAuditLog({
        ctx,
        action: existing ? "listing.category.update" : "listing.category.create",
        entityType: "listing",
        entityId: existing?.id ?? listingId,
        entityLabel: category.name,
        before: existing ?? null,
        after: payload,
        meta: {
          categoryId: category.id,
          categorySlug: category.slug,
          listingType: "category",
        },
      });

      return {
        success: true,
        id: existing?.id ?? listingId,
      };
    }),
});
