import { useEffect, useMemo, useState } from "react";
import { FileSearch, Loader2, Search, ShieldCheck, Sparkles, Type } from "lucide-react";
import { toast } from "sonner";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import AdminSection from "@/components/admin/AdminSection";
import AdminStatCard from "@/components/admin/AdminStatCard";
import { trpc } from "@/providers/trpc";

type ListingFormState = {
  title: string;
  metaDescription: string;
  h1: string;
  introText: string;
  bottomText: string;
  canonicalUrl: string;
  indexationMode: "index" | "noindex" | "canonical_to_parent" | "exclude_from_sitemap";
  seoTextStatus: "empty" | "draft" | "ready" | "published";
  isPublished: boolean;
  isAutoGenerated: boolean;
  demandScore: number;
  duplicateRisk: "low" | "medium" | "high";
};

const EMPTY_FORM: ListingFormState = {
  title: "",
  metaDescription: "",
  h1: "",
  introText: "",
  bottomText: "",
  canonicalUrl: "",
  indexationMode: "index",
  seoTextStatus: "empty",
  isPublished: true,
  isAutoGenerated: false,
  demandScore: 0,
  duplicateRisk: "low",
};

function buildFormState(data?: any): ListingFormState {
  if (!data) return EMPTY_FORM;
  return {
    title: data.title ?? "",
    metaDescription: data.metaDescription ?? "",
    h1: data.h1 ?? "",
    introText: data.introText ?? "",
    bottomText: data.bottomText ?? "",
    canonicalUrl: data.canonicalUrl ?? "",
    indexationMode: data.indexationMode ?? "index",
    seoTextStatus: data.seoTextStatus ?? "empty",
    isPublished: data.isPublished ?? true,
    isAutoGenerated: data.isAutoGenerated ?? false,
    demandScore: data.demandScore ?? 0,
    duplicateRisk: data.duplicateRisk ?? "low",
  };
}

export default function AdminListings() {
  const [search, setSearch] = useState("");
  const [selectedCategoryId, setSelectedCategoryId] = useState<number | null>(null);
  const [form, setForm] = useState<ListingFormState>(EMPTY_FORM);

  const utils = trpc.useUtils();
  const listingsQuery = trpc.listing.listCategoryListings.useQuery({
    search: search.trim() || undefined,
  });

  const items = listingsQuery.data?.items ?? [];
  const summary = listingsQuery.data?.summary;

  useEffect(() => {
    if (!items.length) {
      setSelectedCategoryId(null);
      return;
    }
    setSelectedCategoryId(current =>
      current && items.some(item => item.categoryId === current)
        ? current
        : items[0].categoryId
    );
  }, [items]);

  const selectedItem = useMemo(
    () => items.find(item => item.categoryId === selectedCategoryId) ?? null,
    [items, selectedCategoryId]
  );

  const listingDetailsQuery = trpc.listing.getCategoryListing.useQuery(
    { categoryId: selectedCategoryId ?? 0 },
    { enabled: selectedCategoryId !== null }
  );

  useEffect(() => {
    if (listingDetailsQuery.data) {
      setForm(buildFormState(listingDetailsQuery.data));
    }
  }, [listingDetailsQuery.data]);

  const upsertListing = trpc.listing.upsertCategoryListing.useMutation({
    onSuccess: async () => {
      toast.success("Листинг сохранён");
      await Promise.all([
        utils.listing.listCategoryListings.invalidate(),
        selectedCategoryId
          ? utils.listing.getCategoryListing.invalidate({ categoryId: selectedCategoryId })
          : Promise.resolve(),
      ]);
    },
    onError: error => {
      toast.error(error.message || "Не удалось сохранить листинг");
    },
  });

  const dirty =
    JSON.stringify(form) !== JSON.stringify(buildFormState(listingDetailsQuery.data));

  const handleSave = () => {
    if (!selectedCategoryId) return;
    upsertListing.mutate({
      categoryId: selectedCategoryId,
      data: {
        ...form,
        title: form.title || null,
        metaDescription: form.metaDescription || null,
        h1: form.h1 || null,
        introText: form.introText || null,
        bottomText: form.bottomText || null,
        canonicalUrl: form.canonicalUrl || null,
      },
    });
  };

  return (
    <div className="space-y-6">
      <AdminPageHeader
        eyebrow="Каталог"
        title="Листинги"
        description="Первый контур управления посадочными страницами каталога. Здесь мы держим category pages как отдельные управляемые сущности: контент, индексируемость, canonical и редакторский статус."
        actions={
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => listingsQuery.refetch()}
              className="inline-flex items-center justify-center rounded-full border border-border px-4 py-2 text-sm font-semibold text-foreground transition hover:border-[var(--tech-color-primary)] hover:text-[var(--tech-color-primary)]"
            >
              Обновить
            </button>
          </div>
        }
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <AdminStatCard
          label="Всего листингов"
          value={summary?.total ?? 0}
          hint="Категорийные страницы в контуре"
          icon={FileSearch}
          tone="default"
        />
        <AdminStatCard
          label="С кастомным контентом"
          value={summary?.custom ?? 0}
          hint="Есть отдельная запись listing"
          icon={Type}
          tone="accent"
        />
        <AdminStatCard
          label="Готовы к индексации"
          value={summary?.indexable ?? 0}
          hint="Режим index"
          icon={ShieldCheck}
          tone="success"
        />
        <AdminStatCard
          label="Высокий риск дубля"
          value={summary?.highRisk ?? 0}
          hint="Нужна ручная оценка"
          icon={Sparkles}
          tone="warning"
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(420px,0.9fr)]">
        <AdminSection
          title="Все категорийные листинги"
          description="Пока в контуре только category pages. Filter-pages добавим следующим этапом поверх этой базы."
          actions={
            <label className="relative block w-full max-w-md">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <input
                value={search}
                onChange={event => setSearch(event.target.value)}
                placeholder="Поиск по названию или slug"
                className="h-11 w-full rounded-full border border-border bg-background pl-10 pr-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
              />
            </label>
          }
          contentClassName="p-0"
        >
          <div className="divide-y divide-border/60">
            {listingsQuery.isLoading ? (
              <div className="flex items-center justify-center px-6 py-16 text-sm text-muted-foreground">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Загружаем листинги
              </div>
            ) : items.length === 0 ? (
              <div className="px-6 py-16 text-sm text-muted-foreground">
                Ничего не найдено. Попробуйте изменить запрос.
              </div>
            ) : (
              items.map(item => {
                const selected = item.categoryId === selectedCategoryId;
                return (
                  <button
                    key={item.categoryId}
                    type="button"
                    onClick={() => setSelectedCategoryId(item.categoryId)}
                    className={`grid w-full gap-3 px-6 py-4 text-left transition ${
                      selected
                        ? "bg-[color:color-mix(in_srgb,var(--tech-color-primary)_8%,transparent)]"
                        : "hover:bg-[var(--tech-color-surface-muted)]"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <div className="text-base font-black text-foreground">
                          {item.categoryName}
                        </div>
                        <div className="mt-1 text-xs text-muted-foreground">
                          {item.categorySlug}
                        </div>
                      </div>
                      <span className="rounded-full bg-[var(--tech-color-surface-muted)] px-3 py-1 text-xs font-semibold text-muted-foreground">
                        {item.productCount} тов.
                      </span>
                    </div>
                    <div className="flex flex-wrap items-center gap-2 text-xs">
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        {item.indexationMode}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        {item.seoTextStatus}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        content {item.contentScore}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        demand {item.demandScore}
                      </span>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </AdminSection>

        <AdminSection
          title={selectedItem ? `Листинг: ${selectedItem.categoryName}` : "Карточка листинга"}
          description={
            selectedItem
              ? `URL: ${selectedItem.url}`
              : "Выберите листинг слева, чтобы редактировать контент и правила индексации."
          }
          actions={
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setForm(buildFormState(listingDetailsQuery.data))}
                disabled={!selectedItem || !dirty}
                className="rounded-full border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition disabled:cursor-not-allowed disabled:opacity-50"
              >
                Сбросить
              </button>
              <button
                type="button"
                onClick={handleSave}
                disabled={!selectedItem || upsertListing.isPending || !dirty}
                className="rounded-full bg-[var(--tech-color-primary)] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {upsertListing.isPending ? "Сохраняем..." : "Сохранить"}
              </button>
            </div>
          }
        >
          {!selectedItem || listingDetailsQuery.isLoading ? (
            <div className="flex items-center justify-center py-16 text-sm text-muted-foreground">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Загружаем карточку
            </div>
          ) : (
            <div className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-3xl bg-[var(--tech-color-surface-muted)] p-4">
                  <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                    Категория
                  </div>
                  <div className="mt-2 text-base font-semibold text-foreground">
                    {selectedItem.categoryName}
                  </div>
                  <div className="mt-1 text-sm text-muted-foreground">
                    {selectedItem.categorySlug}
                  </div>
                </div>
                <div className="rounded-3xl bg-[var(--tech-color-surface-muted)] p-4">
                  <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                    Покрытие
                  </div>
                  <div className="mt-2 text-base font-semibold text-foreground">
                    {selectedItem.productCount} товаров
                  </div>
                  <div className="mt-1 text-sm text-muted-foreground">
                    content score {selectedItem.contentScore}, demand score {selectedItem.demandScore}
                  </div>
                </div>
              </div>

              <div className="grid gap-4">
                <Field label="Title">
                  <input
                    value={form.title}
                    onChange={event => setForm(current => ({ ...current, title: event.target.value }))}
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="H1">
                  <input
                    value={form.h1}
                    onChange={event => setForm(current => ({ ...current, h1: event.target.value }))}
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Meta description">
                  <textarea
                    value={form.metaDescription}
                    onChange={event =>
                      setForm(current => ({ ...current, metaDescription: event.target.value }))
                    }
                    rows={4}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Интро">
                  <textarea
                    value={form.introText}
                    onChange={event =>
                      setForm(current => ({ ...current, introText: event.target.value }))
                    }
                    rows={4}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Нижний текст">
                  <textarea
                    value={form.bottomText}
                    onChange={event =>
                      setForm(current => ({ ...current, bottomText: event.target.value }))
                    }
                    rows={5}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <Field label="Режим индексации">
                  <select
                    value={form.indexationMode}
                    onChange={event =>
                      setForm(current => ({
                        ...current,
                        indexationMode: event.target.value as ListingFormState["indexationMode"],
                      }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  >
                    <option value="index">index</option>
                    <option value="noindex">noindex</option>
                    <option value="canonical_to_parent">canonical_to_parent</option>
                    <option value="exclude_from_sitemap">exclude_from_sitemap</option>
                  </select>
                </Field>
                <Field label="Статус текста">
                  <select
                    value={form.seoTextStatus}
                    onChange={event =>
                      setForm(current => ({
                        ...current,
                        seoTextStatus: event.target.value as ListingFormState["seoTextStatus"],
                      }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  >
                    <option value="empty">empty</option>
                    <option value="draft">draft</option>
                    <option value="ready">ready</option>
                    <option value="published">published</option>
                  </select>
                </Field>
                <Field label="Canonical URL">
                  <input
                    value={form.canonicalUrl}
                    onChange={event =>
                      setForm(current => ({ ...current, canonicalUrl: event.target.value }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Risk / demand">
                  <div className="grid grid-cols-[1fr_120px] gap-3">
                    <select
                      value={form.duplicateRisk}
                      onChange={event =>
                        setForm(current => ({
                          ...current,
                          duplicateRisk: event.target.value as ListingFormState["duplicateRisk"],
                        }))
                      }
                      className="h-11 rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    >
                      <option value="low">low</option>
                      <option value="medium">medium</option>
                      <option value="high">high</option>
                    </select>
                    <input
                      type="number"
                      min={0}
                      max={100}
                      value={form.demandScore}
                      onChange={event =>
                        setForm(current => ({
                          ...current,
                          demandScore: Number(event.target.value || 0),
                        }))
                      }
                      className="h-11 rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    />
                  </div>
                </Field>
              </div>
            </div>
          )}
        </AdminSection>
      </div>
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="space-y-2">
      <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
        {label}
      </div>
      {children}
    </label>
  );
}
