import { useEffect, useMemo, useState } from "react";
import {
  FileSearch,
  Loader2,
  Search,
  ShieldCheck,
  Sparkles,
  Type,
  TrendingUp,
  DatabaseZap,
} from "lucide-react";
import { toast } from "sonner";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import AdminSection from "@/components/admin/AdminSection";
import AdminStatCard from "@/components/admin/AdminStatCard";
import { trpc } from "@/providers/trpc";

type ListingFormState = {
  title: string;
  metaDescription: string;
  h1: string;
  introText: string;
  bottomText: string;
  canonicalUrl: string;
  indexationMode: "index" | "noindex" | "canonical_to_parent" | "exclude_from_sitemap";
  seoTextStatus: "empty" | "draft" | "ready" | "published";
  isPublished: boolean;
  isAutoGenerated: boolean;
  demandScore: number;
  duplicateRisk: "low" | "medium" | "high";
};

type DemandClusterFormState = {
  primaryQuery: string;
  supportingQueriesText: string;
  synonymsText: string;
  negativesText: string;
  intent: "commercial" | "informational" | "comparison" | "mixed";
  source:
    | "manual"
    | "internal_search"
    | "search_terms"
    | "yandex_wordstat"
    | "yandex_webmaster"
    | "imported";
  sourceLabel: string;
  impressions: number;
  clicks: number;
  ctr: string;
  avgPosition: string;
  notes: string;
};

const EMPTY_FORM: ListingFormState = {
  title: "",
  metaDescription: "",
  h1: "",
  introText: "",
  bottomText: "",
  canonicalUrl: "",
  indexationMode: "index",
  seoTextStatus: "empty",
  isPublished: true,
  isAutoGenerated: false,
  demandScore: 0,
  duplicateRisk: "low",
};

const EMPTY_DEMAND_FORM: DemandClusterFormState = {
  primaryQuery: "",
  supportingQueriesText: "",
  synonymsText: "",
  negativesText: "",
  intent: "commercial",
  source: "manual",
  sourceLabel: "",
  impressions: 0,
  clicks: 0,
  ctr: "",
  avgPosition: "",
  notes: "",
};

function buildFormState(data?: unknown): ListingFormState {
  if (!data || typeof data !== "object") return EMPTY_FORM;
  const source = data as Record<string, unknown>;
  return {
    title: typeof source.title === "string" ? source.title : "",
    metaDescription:
      typeof source.metaDescription === "string" ? source.metaDescription : "",
    h1: typeof source.h1 === "string" ? source.h1 : "",
    introText: typeof source.introText === "string" ? source.introText : "",
    bottomText: typeof source.bottomText === "string" ? source.bottomText : "",
    canonicalUrl: typeof source.canonicalUrl === "string" ? source.canonicalUrl : "",
    indexationMode:
      source.indexationMode === "noindex" ||
      source.indexationMode === "canonical_to_parent" ||
      source.indexationMode === "exclude_from_sitemap"
        ? source.indexationMode
        : "index",
    seoTextStatus:
      source.seoTextStatus === "draft" ||
      source.seoTextStatus === "ready" ||
      source.seoTextStatus === "published"
        ? source.seoTextStatus
        : "empty",
    isPublished: typeof source.isPublished === "boolean" ? source.isPublished : true,
    isAutoGenerated:
      typeof source.isAutoGenerated === "boolean" ? source.isAutoGenerated : false,
    demandScore: typeof source.demandScore === "number" ? source.demandScore : 0,
    duplicateRisk:
      source.duplicateRisk === "medium" || source.duplicateRisk === "high"
        ? source.duplicateRisk
        : "low",
  };
}

function textToLines(value: string) {
  return value
    .split(/\r?\n|,/)
    .map(item => item.trim())
    .filter(Boolean);
}

function linesToText(value?: string[] | null) {
  return (value ?? []).join("\n");
}

function buildDemandFormState(data?: unknown): DemandClusterFormState {
  if (!data || typeof data !== "object") return EMPTY_DEMAND_FORM;
  const source = data as Record<string, unknown>;
  return {
    primaryQuery: typeof source.primaryQuery === "string" ? source.primaryQuery : "",
    supportingQueriesText: linesToText(
      Array.isArray(source.supportingQueries) ? source.supportingQueries as string[] : []
    ),
    synonymsText: linesToText(
      Array.isArray(source.synonyms) ? source.synonyms as string[] : []
    ),
    negativesText: linesToText(
      Array.isArray(source.negatives) ? source.negatives as string[] : []
    ),
    intent:
      source.intent === "informational" ||
      source.intent === "comparison" ||
      source.intent === "mixed"
        ? source.intent
        : "commercial",
    source:
      source.source === "internal_search" ||
      source.source === "search_terms" ||
      source.source === "yandex_wordstat" ||
      source.source === "yandex_webmaster" ||
      source.source === "imported"
        ? source.source
        : "manual",
    sourceLabel: typeof source.sourceLabel === "string" ? source.sourceLabel : "",
    impressions: typeof source.impressions === "number" ? source.impressions : 0,
    clicks: typeof source.clicks === "number" ? source.clicks : 0,
    ctr:
      typeof source.ctr === "number" || typeof source.ctr === "string"
        ? String(source.ctr)
        : "",
    avgPosition:
      typeof source.avgPosition === "number" || typeof source.avgPosition === "string"
        ? String(source.avgPosition)
        : "",
    notes: typeof source.notes === "string" ? source.notes : "",
  };
}

export default function AdminListings() {
  const [search, setSearch] = useState("");
  const [editorMode, setEditorMode] = useState<"category" | "filter">("category");
  const [selectedCategoryId, setSelectedCategoryId] = useState<number | null>(null);
  const [selectedFilterComposite, setSelectedFilterComposite] = useState<string | null>(null);
  const [filterSearch, setFilterSearch] = useState("");
  const [form, setForm] = useState<ListingFormState>(EMPTY_FORM);
  const [demandForm, setDemandForm] = useState<DemandClusterFormState>(EMPTY_DEMAND_FORM);

  const utils = trpc.useUtils();
  const listingsQuery = trpc.listing.listCategoryListings.useQuery({
    search: search.trim() || undefined,
  });

  const items = useMemo(() => listingsQuery.data?.items ?? [], [listingsQuery.data?.items]);
  const summary = listingsQuery.data?.summary;

  useEffect(() => {
    if (!items.length) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setSelectedCategoryId(null);
      return;
    }
    setSelectedCategoryId(current =>
      current && items.some(item => item.categoryId === current)
        ? current
        : items[0].categoryId
    );
  }, [items]);

  const selectedItem = useMemo(
    () => items.find(item => item.categoryId === selectedCategoryId) ?? null,
    [items, selectedCategoryId]
  );

  const categoryListingDetailsQuery = trpc.listing.getCategoryListing.useQuery(
    { categoryId: selectedCategoryId ?? 0 },
    { enabled: selectedCategoryId !== null && editorMode === "category" }
  );

  const filterCandidatesQuery = trpc.listing.listFilterListingCandidates.useQuery(
    {
      categoryId: selectedCategoryId ?? 0,
      search: filterSearch.trim() || undefined,
    },
    {
      enabled: selectedCategoryId !== null && editorMode === "filter",
    }
  );

  const filterCandidates = useMemo(
    () => filterCandidatesQuery.data ?? [],
    [filterCandidatesQuery.data]
  );
  const selectedFilterCandidate = useMemo(
    () =>
      filterCandidates.find(
        item => `${item.normalizedKey}:${item.normalizedValue}` === selectedFilterComposite
      ) ?? null,
    [filterCandidates, selectedFilterComposite]
  );

  const filterListingDetailsQuery = trpc.listing.getFilterListing.useQuery(
    {
      categoryId: selectedCategoryId ?? 0,
      filterKey: selectedFilterCandidate?.normalizedKey ?? "__disabled__",
      filterValue: selectedFilterCandidate?.normalizedValue ?? "__disabled__",
    },
    {
      enabled:
        selectedCategoryId !== null &&
        editorMode === "filter" &&
        Boolean(selectedFilterCandidate),
    }
  );

  const categoryDemandClusterQuery = trpc.listing.getCategoryDemandCluster.useQuery(
    { categoryId: selectedCategoryId ?? 0 },
    { enabled: selectedCategoryId !== null && editorMode === "category" }
  );

  const filterDemandClusterQuery = trpc.listing.getFilterDemandCluster.useQuery(
    {
      categoryId: selectedCategoryId ?? 0,
      filterKey: selectedFilterCandidate?.normalizedKey ?? "__disabled__",
      filterValue: selectedFilterCandidate?.normalizedValue ?? "__disabled__",
    },
    {
      enabled:
        selectedCategoryId !== null &&
        editorMode === "filter" &&
        Boolean(selectedFilterCandidate),
    }
  );

  useEffect(() => {
    if (editorMode === "category" && categoryListingDetailsQuery.data) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setForm(buildFormState(categoryListingDetailsQuery.data));
    }
    if (editorMode === "filter" && filterListingDetailsQuery.data) {
      setForm(buildFormState(filterListingDetailsQuery.data));
    }
  }, [categoryListingDetailsQuery.data, editorMode, filterListingDetailsQuery.data]);

  useEffect(() => {
    if (editorMode === "category" && categoryDemandClusterQuery.data) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setDemandForm(
        buildDemandFormState(
          categoryDemandClusterQuery.data.current ?? categoryDemandClusterQuery.data.draft
        )
      );
    }
    if (editorMode === "filter" && filterDemandClusterQuery.data) {
      setDemandForm(
        buildDemandFormState(
          filterDemandClusterQuery.data.current ?? filterDemandClusterQuery.data.draft
        )
      );
    }
  }, [categoryDemandClusterQuery.data, editorMode, filterDemandClusterQuery.data]);

  useEffect(() => {
    if (editorMode !== "filter") return;
    if (!filterCandidates.length) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setSelectedFilterComposite(null);
      return;
    }
    setSelectedFilterComposite(current =>
      current && filterCandidates.some(item => `${item.normalizedKey}:${item.normalizedValue}` === current)
        ? current
        : `${filterCandidates[0].normalizedKey}:${filterCandidates[0].normalizedValue}`
    );
  }, [editorMode, filterCandidates]);

  const upsertListing = trpc.listing.upsertCategoryListing.useMutation({
    onSuccess: async () => {
      toast.success("Листинг сохранён");
      await Promise.all([
        utils.listing.listCategoryListings.invalidate(),
        selectedCategoryId
          ? utils.listing.listFilterListingCandidates.invalidate({ categoryId: selectedCategoryId })
          : Promise.resolve(),
        selectedCategoryId
          ? utils.listing.getCategoryListing.invalidate({ categoryId: selectedCategoryId })
          : Promise.resolve(),
        selectedCategoryId && selectedFilterCandidate
          ? utils.listing.getFilterListing.invalidate({
              categoryId: selectedCategoryId,
              filterKey: selectedFilterCandidate.normalizedKey,
              filterValue: selectedFilterCandidate.normalizedValue,
            })
          : Promise.resolve(),
      ]);
    },
    onError: error => {
      toast.error(error.message || "Не удалось сохранить листинг");
    },
  });

  const upsertFilterListing = trpc.listing.upsertFilterListing.useMutation({
    onSuccess: async () => {
      toast.success("Фильтр-листинг сохранён");
      await Promise.all([
        utils.listing.listFilterListingCandidates.invalidate({ categoryId: selectedCategoryId ?? 0 }),
        selectedCategoryId && selectedFilterCandidate
          ? utils.listing.getFilterListing.invalidate({
              categoryId: selectedCategoryId,
              filterKey: selectedFilterCandidate.normalizedKey,
              filterValue: selectedFilterCandidate.normalizedValue,
            })
          : Promise.resolve(),
      ]);
    },
    onError: error => {
      toast.error(error.message || "Не удалось сохранить фильтр-листинг");
    },
  });

  const upsertCategoryDemandCluster = trpc.listing.upsertCategoryDemandCluster.useMutation({
    onSuccess: async () => {
      toast.success("Кластер спроса сохранён");
      await Promise.all([
        selectedCategoryId
          ? utils.listing.getCategoryDemandCluster.invalidate({ categoryId: selectedCategoryId })
          : Promise.resolve(),
        utils.listing.listCategoryListings.invalidate(),
        selectedCategoryId
          ? utils.listing.getCategoryListing.invalidate({ categoryId: selectedCategoryId })
          : Promise.resolve(),
      ]);
    },
    onError: error => {
      toast.error(error.message || "Не удалось сохранить кластер спроса");
    },
  });

  const upsertFilterDemandCluster = trpc.listing.upsertFilterDemandCluster.useMutation({
    onSuccess: async () => {
      toast.success("Кластер спроса сохранён");
      await Promise.all([
        selectedCategoryId && selectedFilterCandidate
          ? utils.listing.getFilterDemandCluster.invalidate({
              categoryId: selectedCategoryId,
              filterKey: selectedFilterCandidate.normalizedKey,
              filterValue: selectedFilterCandidate.normalizedValue,
            })
          : Promise.resolve(),
        utils.listing.listCategoryListings.invalidate(),
      ]);
    },
    onError: error => {
      toast.error(error.message || "Не удалось сохранить кластер спроса");
    },
  });

  const dirty =
    JSON.stringify(form) !==
    JSON.stringify(
      buildFormState(
        editorMode === "category"
          ? categoryListingDetailsQuery.data
          : filterListingDetailsQuery.data
      )
    );

  const activeDemandData =
    editorMode === "category"
      ? categoryDemandClusterQuery.data
      : filterDemandClusterQuery.data;

  const demandDirty =
    JSON.stringify(demandForm) !==
    JSON.stringify(
      buildDemandFormState(activeDemandData?.current ?? activeDemandData?.draft)
    );

  const handleSave = () => {
    if (!selectedCategoryId) return;
    if (editorMode === "category") {
      upsertListing.mutate({
        categoryId: selectedCategoryId,
        data: {
          ...form,
          title: form.title || null,
          metaDescription: form.metaDescription || null,
          h1: form.h1 || null,
          introText: form.introText || null,
          bottomText: form.bottomText || null,
          canonicalUrl: form.canonicalUrl || null,
        },
      });
      return;
    }

    if (!selectedFilterCandidate) return;
    upsertFilterListing.mutate({
      categoryId: selectedCategoryId,
      filterKey: selectedFilterCandidate.normalizedKey,
      filterValue: selectedFilterCandidate.normalizedValue,
      data: {
        ...form,
        title: form.title || null,
        metaDescription: form.metaDescription || null,
        h1: form.h1 || null,
        introText: form.introText || null,
        bottomText: form.bottomText || null,
        canonicalUrl: form.canonicalUrl || null,
      },
    });
  };

  const applyDemandDraft = () => {
    if (!activeDemandData?.draft) return;
    setDemandForm(buildDemandFormState(activeDemandData.draft));
  };

  const handleSaveDemandCluster = () => {
    if (!selectedCategoryId) return;
    const payload = {
      primaryQuery: demandForm.primaryQuery.trim(),
      supportingQueries: textToLines(demandForm.supportingQueriesText),
      synonyms: textToLines(demandForm.synonymsText),
      negatives: textToLines(demandForm.negativesText),
      intent: demandForm.intent,
      source: demandForm.source,
      sourceLabel: demandForm.sourceLabel.trim() || null,
      impressions: Number(demandForm.impressions || 0),
      clicks: Number(demandForm.clicks || 0),
      ctr: demandForm.ctr.trim() ? Number(demandForm.ctr) : null,
      avgPosition: demandForm.avgPosition.trim() ? Number(demandForm.avgPosition) : null,
      notes: demandForm.notes.trim() || null,
    };

    if (editorMode === "category") {
      upsertCategoryDemandCluster.mutate({
        categoryId: selectedCategoryId,
        data: payload,
      });
      return;
    }

    if (!selectedFilterCandidate) return;
    upsertFilterDemandCluster.mutate({
      categoryId: selectedCategoryId,
      filterKey: selectedFilterCandidate.normalizedKey,
      filterValue: selectedFilterCandidate.normalizedValue,
      data: payload,
    });
  };

  return (
    <div className="space-y-6">
      <AdminPageHeader
        eyebrow="Каталог"
        title="Листинги"
        description="Управляем category pages и посадочными страницами вида категория + один фильтр из одной модели: контент, индексируемость, canonical и редакторский статус."
        actions={
          <div className="flex items-center gap-2">
            <div className="inline-flex rounded-full border border-border bg-background p-1">
              <button
                type="button"
                onClick={() => setEditorMode("category")}
                className={`rounded-full px-4 py-2 text-sm font-semibold transition ${
                  editorMode === "category"
                    ? "bg-[var(--tech-color-primary)] text-white"
                    : "text-foreground"
                }`}
              >
                Категории
              </button>
              <button
                type="button"
                onClick={() => setEditorMode("filter")}
                className={`rounded-full px-4 py-2 text-sm font-semibold transition ${
                  editorMode === "filter"
                    ? "bg-[var(--tech-color-primary)] text-white"
                    : "text-foreground"
                }`}
              >
                Категория + фильтр
              </button>
            </div>
            <button
              type="button"
              onClick={() => {
                listingsQuery.refetch();
                filterCandidatesQuery.refetch();
              }}
              className="inline-flex items-center justify-center rounded-full border border-border px-4 py-2 text-sm font-semibold text-foreground transition hover:border-[var(--tech-color-primary)] hover:text-[var(--tech-color-primary)]"
            >
              Обновить
            </button>
          </div>
        }
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <AdminStatCard
          label="Всего листингов"
          value={summary?.total ?? 0}
          hint="Категорийные страницы в контуре"
          icon={FileSearch}
          tone="default"
        />
        <AdminStatCard
          label="С кастомным контентом"
          value={summary?.custom ?? 0}
          hint="Есть отдельная запись listing"
          icon={Type}
          tone="accent"
        />
        <AdminStatCard
          label="Готовы к индексации"
          value={summary?.indexable ?? 0}
          hint="Режим index"
          icon={ShieldCheck}
          tone="success"
        />
        <AdminStatCard
          label="Высокий риск дубля"
          value={summary?.highRisk ?? 0}
          hint="Нужна ручная оценка"
          icon={Sparkles}
          tone="warning"
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(420px,0.9fr)]">
        <AdminSection
          title={
            editorMode === "category"
              ? "Все категорийные листинги"
              : "Категории для filter pages"
          }
          description={
            editorMode === "category"
              ? "Список category pages с fallback на данные категории."
              : "Выберите категорию слева, потом справа настроим конкретную страницу вида категория + один фильтр."
          }
          actions={
            <label className="relative block w-full max-w-md">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <input
                value={search}
                onChange={event => setSearch(event.target.value)}
                placeholder="Поиск по названию или slug"
                className="h-11 w-full rounded-full border border-border bg-background pl-10 pr-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
              />
            </label>
          }
          contentClassName="p-0"
        >
          <div className="divide-y divide-border/60">
            {listingsQuery.isLoading ? (
              <div className="flex items-center justify-center px-6 py-16 text-sm text-muted-foreground">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Загружаем листинги
              </div>
            ) : items.length === 0 ? (
              <div className="px-6 py-16 text-sm text-muted-foreground">
                Ничего не найдено. Попробуйте изменить запрос.
              </div>
            ) : (
              items.map(item => {
                const selected = item.categoryId === selectedCategoryId;
                return (
                  <button
                    key={item.categoryId}
                    type="button"
                    onClick={() => setSelectedCategoryId(item.categoryId)}
                    className={`grid w-full gap-3 px-6 py-4 text-left transition ${
                      selected
                        ? "bg-[color:color-mix(in_srgb,var(--tech-color-primary)_8%,transparent)]"
                        : "hover:bg-[var(--tech-color-surface-muted)]"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <div className="text-base font-black text-foreground">
                          {item.categoryName}
                        </div>
                        <div className="mt-1 text-xs text-muted-foreground">
                          {item.categorySlug}
                        </div>
                      </div>
                      <span className="rounded-full bg-[var(--tech-color-surface-muted)] px-3 py-1 text-xs font-semibold text-muted-foreground">
                        {item.productCount} тов.
                      </span>
                    </div>
                    <div className="flex flex-wrap items-center gap-2 text-xs">
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        {item.indexationMode}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        {item.seoTextStatus}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        content {item.contentScore}
                      </span>
                      <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                        demand {item.demandScore}
                      </span>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </AdminSection>

        <AdminSection
          title={
            editorMode === "category"
              ? selectedItem
                ? `Листинг: ${selectedItem.categoryName}`
                : "Карточка листинга"
              : selectedItem
                ? `Фильтр-листинг: ${selectedItem.categoryName}`
                : "Фильтр-листинг"
          }
          description={
            editorMode === "category"
              ? selectedItem
                ? `URL: ${selectedItem.url}`
                : "Выберите листинг слева, чтобы редактировать контент и правила индексации."
              : selectedFilterCandidate
                ? `${selectedFilterCandidate.key}: ${selectedFilterCandidate.value}`
                : "Выберите категорию, затем конкретный фильтр для посадочной страницы."
          }
          actions={
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() =>
                  setForm(
                    buildFormState(
                      editorMode === "category"
                        ? categoryListingDetailsQuery.data
                        : filterListingDetailsQuery.data
                    )
                  )
                }
                disabled={!selectedItem || !dirty}
                className="rounded-full border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition disabled:cursor-not-allowed disabled:opacity-50"
              >
                Сбросить
              </button>
              <button
                type="button"
                onClick={handleSave}
                disabled={
                  !selectedItem ||
                  !dirty ||
                  (editorMode === "category" ? upsertListing.isPending : upsertFilterListing.isPending)
                }
                className="rounded-full bg-[var(--tech-color-primary)] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {editorMode === "category"
                  ? upsertListing.isPending
                    ? "Сохраняем..."
                    : "Сохранить"
                  : upsertFilterListing.isPending
                    ? "Сохраняем..."
                    : "Сохранить"}
              </button>
            </div>
          }
        >
          {!selectedItem ||
          (editorMode === "category"
            ? categoryListingDetailsQuery.isLoading
            : Boolean(selectedFilterCandidate) && filterListingDetailsQuery.isLoading) ? (
            <div className="flex items-center justify-center py-16 text-sm text-muted-foreground">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Загружаем карточку
            </div>
          ) : (
            <div className="space-y-6">
              {editorMode === "filter" ? (
                <div className="space-y-3 rounded-3xl bg-[var(--tech-color-surface-muted)] p-4">
                  <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
                    <label className="relative block flex-1">
                      <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                      <input
                        value={filterSearch}
                        onChange={event => setFilterSearch(event.target.value)}
                        placeholder="Поиск по значению фильтра"
                        className="h-11 w-full rounded-2xl border border-border bg-background pl-10 pr-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </label>
                    <select
                      value={selectedFilterComposite ?? ""}
                      onChange={event => setSelectedFilterComposite(event.target.value)}
                      className="h-11 min-w-[320px] rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    >
                      {filterCandidates.map(item => (
                        <option
                          key={`${item.normalizedKey}:${item.normalizedValue}`}
                          value={`${item.normalizedKey}:${item.normalizedValue}`}
                        >
                          {item.key}: {item.value} · {item.productCount} тов.
                        </option>
                      ))}
                    </select>
                  </div>
                  {selectedFilterCandidate ? (
                    <div className="flex flex-wrap gap-2 text-xs">
                      <span className="rounded-full border border-border px-3 py-1 text-muted-foreground">
                        {selectedFilterCandidate.key}
                      </span>
                      <span className="rounded-full border border-border px-3 py-1 text-muted-foreground">
                        {selectedFilterCandidate.value}
                      </span>
                      <span className="rounded-full border border-border px-3 py-1 text-muted-foreground">
                        {selectedFilterCandidate.productCount} тов.
                      </span>
                      <span className="rounded-full border border-border px-3 py-1 text-muted-foreground">
                        дубль: {selectedFilterCandidate.duplicateRisk}
                      </span>
                    </div>
                  ) : null}
                </div>
              ) : null}

              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-3xl bg-[var(--tech-color-surface-muted)] p-4">
                  <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                    Категория
                  </div>
                  <div className="mt-2 text-base font-semibold text-foreground">
                    {selectedItem.categoryName}
                  </div>
                  <div className="mt-1 text-sm text-muted-foreground">
                    {selectedItem.categorySlug}
                  </div>
                </div>
                <div className="rounded-3xl bg-[var(--tech-color-surface-muted)] p-4">
                  <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                    Покрытие
                  </div>
                  <div className="mt-2 text-base font-semibold text-foreground">
                    {editorMode === "filter"
                      ? filterListingDetailsQuery.data?.productCount ?? 0
                      : selectedItem.productCount}{" "}
                    товаров
                  </div>
                  <div className="mt-1 text-sm text-muted-foreground">
                    content score{" "}
                    {editorMode === "filter"
                      ? filterListingDetailsQuery.data?.contentScore ?? 0
                      : selectedItem.contentScore}
                    , demand score{" "}
                    {editorMode === "filter"
                      ? filterListingDetailsQuery.data?.demandScore ?? 0
                      : selectedItem.demandScore}
                  </div>
                </div>
              </div>

              <div className="grid gap-4">
                <Field label="Title">
                  <input
                    value={form.title}
                    onChange={event => setForm(current => ({ ...current, title: event.target.value }))}
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="H1">
                  <input
                    value={form.h1}
                    onChange={event => setForm(current => ({ ...current, h1: event.target.value }))}
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Meta description">
                  <textarea
                    value={form.metaDescription}
                    onChange={event =>
                      setForm(current => ({ ...current, metaDescription: event.target.value }))
                    }
                    rows={4}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Интро">
                  <textarea
                    value={form.introText}
                    onChange={event =>
                      setForm(current => ({ ...current, introText: event.target.value }))
                    }
                    rows={4}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Нижний текст">
                  <textarea
                    value={form.bottomText}
                    onChange={event =>
                      setForm(current => ({ ...current, bottomText: event.target.value }))
                    }
                    rows={5}
                    className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <Field label="Режим индексации">
                  <select
                    value={form.indexationMode}
                    onChange={event =>
                      setForm(current => ({
                        ...current,
                        indexationMode: event.target.value as ListingFormState["indexationMode"],
                      }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  >
                    <option value="index">index</option>
                    <option value="noindex">noindex</option>
                    <option value="canonical_to_parent">canonical_to_parent</option>
                    <option value="exclude_from_sitemap">exclude_from_sitemap</option>
                  </select>
                </Field>
                <Field label="Статус текста">
                  <select
                    value={form.seoTextStatus}
                    onChange={event =>
                      setForm(current => ({
                        ...current,
                        seoTextStatus: event.target.value as ListingFormState["seoTextStatus"],
                      }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  >
                    <option value="empty">empty</option>
                    <option value="draft">draft</option>
                    <option value="ready">ready</option>
                    <option value="published">published</option>
                  </select>
                </Field>
                <Field label="Canonical URL">
                  <input
                    value={form.canonicalUrl}
                    onChange={event =>
                      setForm(current => ({ ...current, canonicalUrl: event.target.value }))
                    }
                    className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                  />
                </Field>
                <Field label="Risk / demand">
                  <div className="grid grid-cols-[1fr_120px] gap-3">
                    <select
                      value={form.duplicateRisk}
                      onChange={event =>
                        setForm(current => ({
                          ...current,
                          duplicateRisk: event.target.value as ListingFormState["duplicateRisk"],
                        }))
                      }
                      className="h-11 rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    >
                      <option value="low">low</option>
                      <option value="medium">medium</option>
                      <option value="high">high</option>
                    </select>
                    <input
                      type="number"
                      min={0}
                      max={100}
                      value={form.demandScore}
                      onChange={event =>
                        setForm(current => ({
                          ...current,
                          demandScore: Number(event.target.value || 0),
                        }))
                      }
                      className="h-11 rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    />
                  </div>
                </Field>
              </div>

              <div className="rounded-[32px] border border-border/70 bg-[var(--tech-color-surface-muted)]/60 p-5">
                <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                  <div>
                    <div className="text-sm font-black text-foreground">
                      Кластер спроса
                    </div>
                    <div className="mt-1 max-w-2xl text-sm text-muted-foreground">
                      Храним primary query, supporting queries и сигналы спроса для листинга. Это опорный слой для последующей генерации контента и решений по индексации.
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button
                      type="button"
                      onClick={applyDemandDraft}
                      disabled={!activeDemandData?.draft}
                      className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2 text-sm font-semibold text-foreground transition hover:border-[var(--tech-color-primary)] hover:text-[var(--tech-color-primary)] disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <DatabaseZap className="h-4 w-4" />
                      Подставить из поиска
                    </button>
                    <button
                      type="button"
                      onClick={() =>
                        setDemandForm(
                          buildDemandFormState(
                            activeDemandData?.current ?? activeDemandData?.draft
                          )
                        )
                      }
                      disabled={!demandDirty}
                      className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2 text-sm font-semibold text-muted-foreground transition disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      Сбросить
                    </button>
                    <button
                      type="button"
                      onClick={handleSaveDemandCluster}
                      disabled={
                        !demandForm.primaryQuery.trim() ||
                        !demandDirty ||
                        upsertCategoryDemandCluster.isPending ||
                        upsertFilterDemandCluster.isPending
                      }
                      className="inline-flex items-center gap-2 rounded-full bg-[var(--tech-color-primary)] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <TrendingUp className="h-4 w-4" />
                      {upsertCategoryDemandCluster.isPending || upsertFilterDemandCluster.isPending
                        ? "Сохраняем..."
                        : "Сохранить кластер"}
                    </button>
                  </div>
                </div>

                {activeDemandData ? (
                  <div className="mt-4 grid gap-3 lg:grid-cols-2">
                    <div className="rounded-3xl bg-background p-4">
                      <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                        Черновик из спроса
                      </div>
                      <div className="mt-2 text-sm text-foreground">
                        {activeDemandData.draft.primaryQuery || "Пока нет сигнала"}
                      </div>
                      <div className="mt-3 flex flex-wrap gap-2 text-xs text-muted-foreground">
                        <span className="rounded-full border border-border px-3 py-1">
                          показов {activeDemandData.draft.impressions ?? 0}
                        </span>
                        <span className="rounded-full border border-border px-3 py-1">
                          кликов {activeDemandData.draft.clicks ?? 0}
                        </span>
                        <span className="rounded-full border border-border px-3 py-1">
                          CTR {activeDemandData.draft.ctr ?? 0}%
                        </span>
                        <span className="rounded-full border border-border px-3 py-1">
                          source {activeDemandData.draft.source}
                        </span>
                      </div>
                    </div>
                    <div className="rounded-3xl bg-background p-4">
                      <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
                        Внутренний поиск
                      </div>
                      <div className="mt-2 space-y-2 text-sm">
                        {(activeDemandData.suggestions.searchLogSignals ?? [])
                          .slice(0, 4)
                          .map(item => (
                            <div key={`log-${item.query}`} className="flex items-center justify-between gap-4">
                              <span className="truncate text-foreground">{item.query}</span>
                              <span className="shrink-0 text-xs text-muted-foreground">
                                {item.impressions} / {item.clicks}
                              </span>
                            </div>
                          ))}
                        {!(activeDemandData.suggestions.searchLogSignals ?? []).length ? (
                          <div className="text-muted-foreground">
                            Пока нет совпадающих запросов из search_logs.
                          </div>
                        ) : null}
                      </div>
                    </div>
                  </div>
                ) : null}

                <div className="mt-5 grid gap-4">
                  <Field label="Primary query">
                    <input
                      value={demandForm.primaryQuery}
                      onChange={event =>
                        setDemandForm(current => ({
                          ...current,
                          primaryQuery: event.target.value,
                        }))
                      }
                      className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    />
                  </Field>

                  <div className="grid gap-4 lg:grid-cols-3">
                    <Field label="Supporting queries">
                      <textarea
                        value={demandForm.supportingQueriesText}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            supportingQueriesText: event.target.value,
                          }))
                        }
                        rows={6}
                        className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                    <Field label="Synonyms">
                      <textarea
                        value={demandForm.synonymsText}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            synonymsText: event.target.value,
                          }))
                        }
                        rows={6}
                        className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                    <Field label="Negatives">
                      <textarea
                        value={demandForm.negativesText}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            negativesText: event.target.value,
                          }))
                        }
                        rows={6}
                        className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                  </div>

                  <div className="grid gap-4 lg:grid-cols-3">
                    <Field label="Intent">
                      <select
                        value={demandForm.intent}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            intent: event.target.value as DemandClusterFormState["intent"],
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      >
                        <option value="commercial">commercial</option>
                        <option value="informational">informational</option>
                        <option value="comparison">comparison</option>
                        <option value="mixed">mixed</option>
                      </select>
                    </Field>
                    <Field label="Source">
                      <select
                        value={demandForm.source}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            source: event.target.value as DemandClusterFormState["source"],
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      >
                        <option value="manual">manual</option>
                        <option value="internal_search">internal_search</option>
                        <option value="search_terms">search_terms</option>
                        <option value="yandex_wordstat">yandex_wordstat</option>
                        <option value="yandex_webmaster">yandex_webmaster</option>
                        <option value="imported">imported</option>
                      </select>
                    </Field>
                    <Field label="Source label">
                      <input
                        value={demandForm.sourceLabel}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            sourceLabel: event.target.value,
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                  </div>

                  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                    <Field label="Impressions">
                      <input
                        type="number"
                        min={0}
                        value={demandForm.impressions}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            impressions: Number(event.target.value || 0),
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                    <Field label="Clicks">
                      <input
                        type="number"
                        min={0}
                        value={demandForm.clicks}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            clicks: Number(event.target.value || 0),
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                    <Field label="CTR">
                      <input
                        value={demandForm.ctr}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            ctr: event.target.value,
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                    <Field label="Avg position">
                      <input
                        value={demandForm.avgPosition}
                        onChange={event =>
                          setDemandForm(current => ({
                            ...current,
                            avgPosition: event.target.value,
                          }))
                        }
                        className="h-11 w-full rounded-2xl border border-border bg-background px-4 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                      />
                    </Field>
                  </div>

                  <Field label="Notes">
                    <textarea
                      value={demandForm.notes}
                      onChange={event =>
                        setDemandForm(current => ({
                          ...current,
                          notes: event.target.value,
                        }))
                      }
                      rows={4}
                      className="w-full rounded-3xl border border-border bg-background px-4 py-3 text-sm text-foreground outline-none transition focus:border-[var(--tech-color-primary)]"
                    />
                  </Field>
                </div>
              </div>
            </div>
          )}
        </AdminSection>
      </div>
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="space-y-2">
      <div className="text-[11px] font-black uppercase tracking-[0.16em] text-muted-foreground">
        {label}
      </div>
      {children}
    </label>
  );
}
